# Generated by Django 2.1.5 on 2019-06-08 17:23

from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190607_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='stay',
            field=models.DurationField(default=timedelta(hours=3)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
