# Generated by Django 2.1.5 on 2019-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20190608_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stay',
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(None, '---- booking status ----'), ('failed', 'Failed'), ('success', 'Success'), ('inprogress', 'Inprogress')], default='inprogress', max_length=100),
        ),
    ]
